image: clojure:latest

stages:
  - test
  - deploy_staging
  - deploy_production

test:
  stage: test
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_DB: $DB_TEST
    POSTGRES_USER: $DB_TEST_USER
    POSTGRES_PASSWORD: "$DB_TEST_PASSWORD"
    POSTGRES_HOST_AUTH_METHOD: trust
  before_script:
    - PATH=$PATH:.
    - mv resources/database.sample.edn resources/database.edn
    - mv resources/secrets.sample.edn resources/secrets.edn
    - lein deps
    - mkdir /root/uploads
  script:
    - lein migrate
    - lein test

deploy_staging:
  stage: deploy_staging
  variables:
    ENV: "staging"
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp scripts/setup_receive.sh root@"$SSH_IP":~/
    - ssh root@"$SSH_IP" "chmod +x ~/setup_receive.sh && ~/setup_receive.sh ${ENV}"
  only:
    - master

deploy_production:
  stage: deploy_production
  variables:
    ENV: "production"
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp scripts/setup_receive.sh root@"$SSH_IP":~/
    - ssh root@"$SSH_IP" "chmod +x ~/setup_receive.sh && ~/setup_receive.sh ${ENV}"
  only:
    - master
  when: manual
